provider_settings:
  openai:
    model: "gpt-3.5-turbo"  # Mais barato na OpenAI
    api_key_name: "OPENAI_API_KEY"
    api_url: "https://api.openai.com/v1/chat/completions"

  anthropic:
    model: "claude-3-haiku-20240307"  # Mais barato da série Claude 3
    api_key_name: "ANTHROPIC_API_KEY"
    api_url: "https://api.anthropic.com/v1/messages"

  google:
    model: "gemini-pro"  # Modelo padrão e mais barato
    api_key_name: "GOOGLE_API_KEY"
    api_url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"

  deepseek:
    model: "deepseek-chat"  # Atualmente é o modelo público e econômico
    api_key_name: "DEEPSEEK_API_KEY"
    api_url: "https://api.deepseek.com/v1/chat/completions"

  grok:
    model: "grok-1"  # Modelo mais básico conhecido da X.AI
    api_key_name: "GROK_API_KEY"
    api_url: "https://api.x.ai/v1/chat/completions"

model_settings:

  # Define o parâmetro que limita o número máximo de tokens na resposta gerada pelo modelo
  max_tokens: 20  

  # Define o parâmetro que controla a aleatoriedade das respostas geradas pelo modelo
  temperature: 0.7  

  # Define o parâmetro que controla a diversidade das respostas geradas pelo modelo
  top_p: 0.5  

  # Mensagem inicial do sistema
  system_content: "Seja direto e sucinto, sem formatação Markdown."

  # Mensagem inicial do usuário (pode ser vazio)
  user_content: "Explique IA em uma frase."

logger:
  file:
    enabled: true
    level: "DEBUG"
    path: "logs/app.log"
  console:
    level: "INFO"
  suppress:
    - "pandas only supports SQLAlchemy connectable"
  ignore_libs:
    - "httpx"
